# Generated by Django 3.2.14 on 2022-08-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='approval_status',
            new_name='approval_Status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assigned_manager',
            new_name='assigned_Manager',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_date',
            new_name='created_Date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='end_time',
            new_name='end_Time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='start_time',
            new_name='start_Time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_description',
            new_name='task_Description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
